# Generated by Django 5.2.4 on 2025-08-06 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestsandDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Crop', 'Crop'), ('Livestock', 'Livestock'), ('Equipment', 'Equipment'), ('Other', 'Other')], max_length=20)),
                ('crop', models.CharField(blank=True, choices=[('Corn', 'Corn'), ('Soybean', 'Soybean'), ('Maize', 'Maize'), ('Cotton', 'Cotton'), ('Other', 'Other')], max_length=20, null=True)),
                ('livestock', models.CharField(blank=True, choices=[('Cow', 'Cow'), ('Pig', 'Pig'), ('Sheep', 'Sheep'), ('Other', 'Other')], max_length=20, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='pestsanddiseases_videos/')),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PestsandDiseasesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pestsanddiseases_photos/')),
                ('pestsanddiseases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='farmerhub.pestsanddiseases')),
            ],
        ),
        migrations.DeleteModel(
            name='PestDisease',
        ),
    ]
