# Generated by Django 5.2.4 on 2025-08-10 13:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0004_pestsanddiseases_pestsanddiseasesphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestsanddiseases',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
