# Generated by Django 5.2.4 on 2025-08-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0006_alter_pestsanddiseases_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestsanddiseases',
            name='crop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pestsanddiseases',
            name='livestock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='crop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='livestock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
