# Generated by Django 5.2.4 on 2025-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0007_alter_pestsanddiseases_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestsanddiseases',
            name='crop',
            field=models.CharField(blank=True, choices=[('Corn', 'Corn'), ('Soybean', 'Soybean'), ('Maize', 'Maize'), ('Cotton', 'Cotton'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pestsanddiseases',
            name='livestock',
            field=models.CharField(blank=True, choices=[('Cow', 'Cow'), ('Pig', 'Pig'), ('Sheep', 'Sheep'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='crop',
            field=models.CharField(blank=True, choices=[('Corn', 'Corn'), ('Soybean', 'Soybean'), ('Maize', 'Maize'), ('Cotton', 'Cotton'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='equipment',
            field=models.CharField(blank=True, choices=[('Hoe', 'Hoe'), ('Drill', 'Drill'), ('Caterpillar', 'Caterpillar'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='livestock',
            field=models.CharField(blank=True, choices=[('Cow', 'Cow'), ('Pig', 'Pig'), ('Sheep', 'Sheep'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
