# Generated by Django 5.2.4 on 2025-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0009_alter_pestsanddiseases_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tip_photos/'),
        ),
    ]
