# Generated by Django 5.2.4 on 2025-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0011_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audios/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
