# Generated by Django 5.2.4 on 2025-08-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0012_chatmessage_audio_chatmessage_file_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
