# Generated by Django 5.2.4 on 2025-08-17 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0015_trainingvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingvideo',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='training_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
