# Generated by Django 5.2.4 on 2025-08-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0017_marketprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketPrice',
        ),
    ]
