# Generated by Django 5.2.4 on 2025-08-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0018_delete_marketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('mahindi', 'Mahindi'), ('mchele', 'Mchele'), ('maharage', 'Maharage'), ('mtama', 'Mtama'), ('uwele', 'Uwele'), ('ulezi', 'Ulezi'), ('viazi', 'Viazi mviringo'), ('ngombe', 'Ng’ombe'), ('mbuzi', 'Mbuzi'), ('kuku', 'Kuku')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Bei kwa kilo / moja (TZS)', max_digits=10)),
                ('region', models.CharField(blank=True, help_text='Mkoa husika (hiari)', max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='updated_at',
        ),
    ]
