# Generated by Django 5.2.4 on 2025-08-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerhub', '0019_marketprice_remove_trainingvideo_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketPrice',
        ),
    ]
